apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-argocd-application-controller
  namespace: namespace-gitops-test-check1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-controller
subjects:
- kind: ServiceAccount
  name: custom-gitops-argocd-application-controller
  namespace: custom-gitops
